Major help system upgrade.

diff --git a/shortcut_commands/awsassignip b/shortcut_commands/awsassignip
--- a/shortcut_commands/awsassignip
+++ b/shortcut_commands/awsassignip
@@ -1,10 +1,47 @@
 #!/bin/bash
 
+usage=$(cat <<USAGEBLOCK
+Usage:
+$(basename $0) <instance id or tag Name> <Elastic IP address>
+
+Assign elastic IP address to an instance.
+Elastic IP address should be created in AWS beforehand.
+See for details:
+http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html
+
+OPTIONS
+    -h, --help  display this help.
+USAGEBLOCK
+)
+
+
 if [[ $# < 2 ]]; then
-    echo "Usage: $(basename $0) <instance id or tag Name> <Elastic IP address>"
+    echo "$usage"
     exit 1
 fi
 
+I=1
+while test $# -gt 0; do
+    case "$1" in
+        -h | --help)
+            echo "$usage"
+            exit 0
+            ;;
+        --)
+            shift
+            break;;
+        -*)
+            echo "Invalid option: $1"
+            echo "$usage"
+            exit 1;;
+         *)
+            eval export arg$I=$1
+            ((I++))
+            ;;
+    esac
+    shift
+done
+
 # Get ID by ID or tag
-ID="$(awsls -t $1 | awk '{ print $1 }')"
-aws ec2 associate-address --instance-id $ID --public-ip $2 --allow-reassociation
+ID="$(awsls -t $arg1 | awk '{ print $1 }')"
+aws ec2 associate-address --instance-id $ID --public-ip $arg2 --allow-reassociation
