Refreshed AWS EC2 CLI commands.

diff --git a/shortcut_commands/awsls b/shortcut_commands/awsls
--- a/shortcut_commands/awsls
+++ b/shortcut_commands/awsls
@@ -1,19 +1,58 @@
 #!/bin/bash
-# Print ID, State and Tags for all instances.
-# With -s option print only IDs.
-# With instance ID (and option -s) show only information for given instance.
+# Prints ID, State and Tags for all instances.
+# With -t option prints only IDs and Name tags.
+# With instance ID after option -t shows only Name tag for the given instance.
 
-if [[ $# -lt 1 ]]; then
-	LS="$(aws ec2 describe-instances --query 'Reservations[*].{ID:Instances[*].InstanceId,TAG:Instances[*].Tags,STATE:Instances[*].State.Name}' --output text)"
-	# Highlight IDs
-	esc=$(printf '\033')
-	echo "$LS" | sed -r "s/^ID\s*[a-z0-9\-]*/${esc}[48;5;237m${esc}[38;5;208m&${esc}[0m/"
-elif [[ "$1" == "-s" ]]; then
-	if [[ -z "$2" ]]; then
+usage=$(cat <<USAGEBLOCK
+Usage:
+$(basename $0) [-t [<instance ID>]]
+
+With no options prints ID, State and Tags for all instances.
+With -t option prints only IDs and Name tags.
+With instance ID after option -t shows only Name tag for the given instance.
+USAGEBLOCK
+)
+
+while test $# -gt 0; do
+    case "$1" in
+        -h | --help)
+            echo "$usage"
+            exit 0
+            ;;
+        -t)
+			PRINT_TAG="1"
+			ID="$2";shift;
+            ;;
+        --)
+            shift
+            break;;
+        -*)
+            echo "Invalid option: $1"
+            echo "$usage"
+            exit 1;;
+    esac
+    shift
+done
+
+#echo "PRINT_TAG=$PRINT_TAG, ID=$ID."
+
+if [[ -z "$PRINT_TAG" ]]; then
+	LS=$(aws ec2 describe-instances --output json | jq -r -c ".Reservations[] | .Instances[] | [.InstanceId, .State.Name, .KeyName,.ImageId] | @csv" | sed 's/\"//g')
+	arr=( $(echo "$LS") )
+	FORMAT='%-20s\t%-15s\t%-15s\t%-20s\t%-15s\t%-15s\n'
+	printf $FORMAT "ID" "TAG" "STATE" "IP" "KEY" "IMAGE"
+	for line in "${arr[@]}"; do
+		IFS=$','; words=( $(echo "$line") )
+		ID=${words[0]}
+		TAG=$(awstag $ID)
+		IP=$(aws ec2 describe-instances --instance-ids $ID --query 'Reservations[0].Instances[0].PublicIpAddress')
+		printf $FORMAT "$ID" "$TAG" "${words[1]}" "$IP" "${words[2]}" "${words[3]}"
+	done
+else
+	if [[ -z "$ID" ]]; then
 		aws ec2 describe-tags --output text | awk '{ print $3"\t"$5 }'
-	else 
-		aws ec2 describe-tags --filter "Name=resource-id,Values=$2" --output text | awk '{ print $3"\t"$5 }'
+	else
+		aws ec2 describe-tags --filter "Name=resource-id,Values=$ID" --output text | awk '{ print $3"\t"$5 }'
 	fi
 fi
 
- 
diff --git a/shortcut_commands/awsrun b/shortcut_commands/awsrun
--- a/shortcut_commands/awsrun
+++ b/shortcut_commands/awsrun
@@ -1,23 +1,75 @@
 #!/bin/bash
-# Launch new instance and assign it Name tag
+# Launch new instances and assign them Name tags
 
-usage="Usage: $(basename $0) <launch parameters json file> [<tag>]"
-if [[ $# -le 0 ]]; then 
+usage=$(cat <<USAGEBLOCK
+Launch new AWS EC2 instances.
+
+Usage:
+$(basename $0) -f <launch parameters json file> [-n <number>] [-t <name tag base>]
+Options:
+	-f	JSON file with launch parameters. You can generate sample file with command: aws ec2 run-instances --generate-cli-skeleton.
+	-n	Number of instances to launch.
+	-t	Assign the new instances Name tags with this tag base and a number. E.g. -t name will run instances: "name_1", "name_2", ...
+USAGEBLOCK
+)
+
+if [[ $# < 1 ]]; then
+    echo "$usage"
+    exit 1
+fi
+
+# Defaults
+# Number of instances to launch
+N=1
+
+while test $# -gt 0; do
+    case "$1" in
+        -h | --help)
+            echo "$usage"
+            exit 0
+            ;;
+        -f)
+            FILE="$2";shift;
+            ;;
+        -n)
+            N="$2";shift;
+            ;;
+        -t)
+            NAME_TAG="$2";shift;
+            ;;
+        --)
+            shift
+            break;;
+        -*)
+            echo "Invalid option: $1"
+            echo "$usage"
+            exit 1;;
+    esac
+    shift
+done
+
+if [[ -z "$FILE" ]]; then
+	echo "Need JSON file name."
 	echo "$usage"
-	exit 0
-elif [[ $# -eq 1 ]]; then
-	aws ec2 run-instances --cli-input-json file://$1
-else
-	echo "Start and assign tag $2"
-	output="$(aws ec2 run-instances --cli-input-json file://$1 --output text)"	
+	exit 1
+fi
+
+set -e
+
+for i in $(seq 1 $N); do
+	echo $i
+	output="$(aws ec2 run-instances --cli-input-json file://$FILE --output text)"
 	ID="$( eval 'echo "$output"' | grep 'INSTANCES' | awk '{print $7}')"
 	if [[ -z "$ID" ]]; then
 		echo "Couldnt get instance ID from :"
 		echo "$output"
 		exit 1
-	else
-		echo "Started with ID $ID"	
 	fi
-	awstag $ID $2
-	aws ec2 describe-tags --output text | grep "$ID"
-fi
+	echo "Started with ID $ID"
+	echo "IP: $(awsip $ID)"
+	if [ $N -gt 1 ] && [ -n "$NAME_TAG" ]; then
+		TAG="$NAME_TAG_$N"
+		awstag $ID $TAG
+		aws ec2 describe-tags --output text | grep "$ID"
+	fi
+done
